services:
  redis:
    image: eqalpha/keydb:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis.conf:/etc/keydb/keydb.conf
    command: keydb-server /usr/local/etc/redis/redis.conf #switch to redis-server for redis

  game-server:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RUST_LOG=INFO
  map:
    build:
        context: ../map-for-andre
        dockerfile: Dockerfile
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=production

volumes:
  redis_data: