services:
  redis:
    image: redis:7.2-alpine3.19
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

volumes:
  redis_data: