services:
  redis:
    image: eqalpha/keydb:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis.conf:/etc/keydb/keydb.conf
    command: keydb-server /usr/local/etc/redis/redis.conf #switch to redis-server for redis

volumes:
  redis_data: